name: Test Install Script

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - run: make test

      - run: dash -x install.sh
      - run: codecrafters --version
